/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/dhcp6c
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/akmd8963
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mobile_log_d
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mtkrildmd2
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/test/slcryption/sl_sec_encode
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/test/slversion/slver
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/test/fpsvcd/auto_test.sh
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/test/fpsvcd/fpsvcd_s
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/test/fpsvcd/fpsvcd_c
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/program_binary_service
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/boot_logo_updater
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mtk_agpsd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/pq
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/tiny_swapoff
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/tertestclient
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/pppd_btdun
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/meta_tst
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/wifi2agps
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/memorydumper
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/msensord
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/tiny_swapon
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/akmd8975
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/permission_check
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mfv_ut
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/ami304d
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/orientationd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/run-as
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mc6420d
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/nvram_agent_binder
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/racoon
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/memsicd3416x
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/ppl_agent
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/em_svr
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/hostapd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/batterywarning
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/bmm050d
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/audiocmdservice_atci
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/fuelgauged
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/thermald
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/akmd09911
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/6620_wmt_concurrency
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/pppd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/factory
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/md_ctrl
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mmp
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/gsm0710muxdmd2
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/wmt_loader
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/pppd_dt
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/dhcp6ctl
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/aee_archive
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/netdiag
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/nvram_daemon
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/rtt
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mtk_setprop
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/ccci_fsd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/btlogmask
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/gsm0710muxd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/AcdApiDaemon
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/tiny_mkswap
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/6620_launcher
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/MtkCodecService
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/6620_wmt_lpbk
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/s62xd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/fotabinder
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/magd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/muxreport
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/fsck_msdos_mtk
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mdlogger
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/ccci_mdinit
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/memsicd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/aee
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/thermal_manager
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/terservice
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/perf_native_test
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/dualmdlogger
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/dhcp6s
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/geomagneticd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mtkrild
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/sn
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/btconfig
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/mtkbt
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/xlog
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/matv
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/dmlog
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/atcid
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/aee_dumpstate
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/guiext-server
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/kpoc_charger
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/autokd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/badblocks
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/lsm303md
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/thermal
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/fpsvcd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/lcdc_screen_cap
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/radvd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/aosinfo
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/make_ext4fs
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/netcfg
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/hostapd_cli
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/atci_service
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/bin/emdlogger1
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/usr/keylayout/AVRCP.kl
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/usr/keylayout/mtk-kpd.kl
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/usr/keylayout/ACCDET.kl
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-tree7-wmd.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/pittpatt/models/recognition/face.face.y0-y0-71-N-tree_7-wmd.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/media/PFFprec_600.emd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/media/LMspeed_508.emd
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/mediadrm/libdrmclearkeyplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/mediadrm/libwvdrmengine.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/libwvm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/drm/libdrmwvmplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/hw/bluetooth.blueangel.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/hw/audio.a2dp.blueangel.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/libWVStreamControlAPI_L3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib/libwvdrm_L3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/mddb/DbgInfo_LR9.W1444.MD.LWTG.MP_LENTEK6735M_65C_L_LWG_DSDS_MOLY_LR9_W1444_MD_LWTG_MP_V8_P2_2015_06_03_09_50_1_lwg_n
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/mddb/BPLGUInfoCustomAppSrcP_MT6735_S00_MOLY_LR9_W1444_MD_LWTG_MP_V8_P2_1_lwg_n
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/bluetooth/btconfig.xml
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/bluetooth/auto_pair_blacklist.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/bluetooth/bt_stack.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/bluetooth/bt_did.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/bluetooth/auto_pair_devlist.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/wifi/wpa_supplicant.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/wifi/p2p_supplicant_overlay.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/wifi/wpa_supplicant_overlay.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/custom.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/mtk_omx_core.cfg
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/catcher_filter_1_lwg_n.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/modem_1_lwg_n.img
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/S_ANDRO_SFL.ini
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/WIFI_RAM_CODE_6735
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/dsp_1_lwg_n.bin
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/firmware/WMT_SOC.cfg
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/silead/silead_config.xml
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/silead/log_cfg.xml
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/silead/silead_param.xml
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/clatd.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/fmr/mt6627_fm_cust.cfg
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/mtklog-config.prop
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/dhcpcd/dhcpcd-hooks/95-configured
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/dhcpcd/dhcpcd-run-hooks
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/etc/radvd/radvd.conf
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaudiosetting.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libexttestmode.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libPQDCjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.exif.v3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfeatureiodrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnvramagentclient.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libJniAtvService.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libslfpjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libacdk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_usb_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libshowlogo.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbluetoothem_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmmsdkservice.feature.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtsession.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvie_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcameracustom.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libui_ext.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtpcm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libjni_pq.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcamera_client_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnvram_daemon_callback.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtkjpeg.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaudiomtkdcremoval.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libperfservicenative.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libimageio.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libperfservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtkbtextspp.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfeatureio.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxGsmDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam3_app.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/librilmtkmd2.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libpppbtdun.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.jni.lomohaljni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.camshot.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmediatek_exceptionlog.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnvram.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libHEVCdec_sa.ca7.android.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvp8enc_sa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnvram_sec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmmsdkservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libja3m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libhotknot_vendor.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libjtranscode.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbessurround_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtstd.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libSwJpgCodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.metadata.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libdpframework.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libsileadinc_dev.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/lib3a_sample.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libblisrc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libJpgDecPipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtsniff.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaudiodcrflt.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/drm/libdrmmtkplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/drm/libdrmctaplugin.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_lte_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxAdpcmEnc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmhalImageCodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.iopipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libpalsecurity.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.device1.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam_hwutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaal.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/librilmtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmnl.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvoicerecognition.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcameraservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnetutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libJpgEncPipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaudiocustparam.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libdcfdecoderjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtk_mmutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnvram_platform.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_sensor_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvc1dec_sa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libsec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.halsensor.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmpojni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmatv_cust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbluetoothdrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmmsdkservice.feature_platform.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam_mmp.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libjni_lomoeffect.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libdirect-coredump.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmpodecoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxG711Dec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libgraphite2.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libssladp.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaed.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libextsys_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtk_drvb.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfmmt6627.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/egl/libGLES_mali.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/egl/egl.cfg
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnfc_ndef.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libimageio_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfmmt6620.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaudiocomponentengine.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvcodec_utility.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libatvctrlservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.hal3a.v3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxAlacDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libstagefrighthw.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.client.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libgifEncoder_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvp8dec_sa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.iopipe_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfmmt6628.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/mtk-rilmd2.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_modem_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.camnode.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/camera.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/audio.primary.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/gps.default.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/sensors.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/gralloc.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/hwcomposer.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/hw/lights.default.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.exif.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_bt_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/liba3m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtklimiter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libimageio_plat_drv_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtcloader.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam1_utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxFlacDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcamdrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libtinyxml.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfgauge.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam3_pipeline.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam_utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libtouchfilter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_gpio_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libtinycompress.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libpalwlan_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxVenc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxAdpcmDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcustom_nvram.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libblisrc32.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libPQjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libtimestretch.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libdngop.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtcusttable.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libspeech_enh_lib.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtkshifter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkVideoSpeedEffect.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmemoryDumpEncoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvp9dec_sa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam_platform.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libh264enc_sb.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libnativecheck-jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libm4u.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam3_hwnode.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvcodecdrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtb.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libGdmaScalerPipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcamdrv_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcamera_client.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfmjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcamalgo.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libgui_ext.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkVideoTranscoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/lib3a.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libatciserv_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/mtk-ril.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmdloggerrecycle.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libtinyalsa.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxMp3Dec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtem.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libimageio_plat_drv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libion.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libion_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libdrmmtkutil.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_wifi_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxRawDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmp4enc_xa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmpoencoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libccci_util.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.camadapter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.utils.sensorlistener.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmmprofile.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libui.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfile_op.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libged.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.metadataprovider.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbluetooth_relayer.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxVorbisEnc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libadpcm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.campipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcustom_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libBnMtkCodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libextsys.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmemorydumper.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libhotknot.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libpq_cust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxVdec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libsbccodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtcusttc1.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmpo.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.paramsmgr.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmp4enc_sa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.hal3a.v3.dng.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcvsd_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvie.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmtkplayer.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcamera_metadata.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmsbc_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libh264enc_sa.ca7.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfmcust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxApeDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.device3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbwc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbluetooth_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam3_hwpipeline.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libdrmmtkwhitelist.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libudf.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libn3d3a.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libAGifEncoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.utils.cpuctrl.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libfmmt6630.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvoicerecognition_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam3_utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbessound_hd_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcam.sdkclient.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libbtcust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libhwm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libgpu_aux.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libvcodec_oal.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libMtkOmxCore.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libem_support_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libaudiocompensationfilter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcustom_prop.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libpq_prot.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libcurl.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib/libmmprofile_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/xbin/mnld
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/xbin/BGW
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiosetting.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libPQDCjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.exif.v3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfeatureiodrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnvramagentclient.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libslfpjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libacdk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_usb_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbluetoothem_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmmsdkservice.feature.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcameracustom.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libui_ext.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libjni_pq.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcamera_client_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnvram_daemon_callback.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtkjpeg.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfpsvc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libperfservicenative.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libimageio.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libperfservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfeatureio.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxGsmDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam3_app.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/librilmtkmd2.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libpppbtdun.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.jni.lomohaljni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.camshot.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libextem.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmediatek_exceptionlog.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnvram.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnvram_sec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaslxml.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmmsdkservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libja3m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libhotknot_vendor.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbtstd.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libSwJpgCodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.metadata.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libsysutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libdpframework.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libsileadinc_dev.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/lib3a_sample.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libblisrc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libJpgDecPipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiodcrflt.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_lte_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxAdpcmEnc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmhalImageCodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.iopipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.device1.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam_hwutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaal.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/librilmtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiopolicymanagerdefault.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcameraservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnetutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libJpgEncPipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiocustparam.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiopolicymanager.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libdcfdecoderjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtk_mmutils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnvram_platform.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_sensor_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.halsensor.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmatv_cust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbluetoothdrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmmsdkservice.feature_platform.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam_mmp.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libjni_lomoeffect.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libdirect-coredump.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxG711Dec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libgraphite2.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaed.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libextsys_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtk_drvb.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfmmt6627.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/egl/libGLES_mali.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnfc_ndef.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libimageio_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libterservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfmmt6620.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtksqlite3_custom.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiocomponentengine.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libatvctrlservice.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.hal3a.v3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxAlacDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libstagefrighthw.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.client.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.iopipe_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfmmt6628.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/mtk-rilmd2.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_modem_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.camnode.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/camera.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/audio.primary.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/gps.default.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/sensors.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/gralloc.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/hwcomposer.mt6735m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/hw/lights.default.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.exif.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_bt_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/liba3m.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtklimiter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libimageio_plat_drv_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam1_utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcamdrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libtinyxml.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfpsvcd_remoteapi.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam3_pipeline.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libslbase.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam_utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libslfpauth.a
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libtouchfilter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_gpio_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libtinycompress.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxAdpcmDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcustom_nvram.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libblisrc32.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libPQjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libdngop.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbtcusttable.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libspeech_enh_lib.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtkshifter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmemoryDumpEncoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libslos.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam_platform.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libnativecheck-jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libm4u.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam3_hwnode.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libvcodecdrv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libGdmaScalerPipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcamdrv_FrmB.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcamera_client.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfmjni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcamalgo.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libgui_ext.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libwapi.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkVideoTranscoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libslcryption.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/lib3a.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libatciserv_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/mtk-ril.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmdloggerrecycle.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/liblogwrap.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxMp3Dec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbtem.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libextadvanced_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libimageio_plat_drv.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libion.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libion_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libdrmmtkutil.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtksqlite3_android.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_wifi_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxRawDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmpoencoder.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libccci_util.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.camadapter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.utils.sensorlistener.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmmprofile.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libui.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfile_op.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libged.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.metadataprovider.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libwifitest.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbluetooth_relayer.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxVorbisEnc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.campipe.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfpcal.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcustom_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libBnMtkCodec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libextsys.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmemorydumper.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libhotknot.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libpq_cust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmpo.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.paramsmgr.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.hal3a.v3.dng.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcvsd_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmtkplayer.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcamera_metadata.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmsbc_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfmcust.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxApeDec.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.device3.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbwc.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbluetooth_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam3_hwpipeline.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libdrmmtkwhitelist.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libudf.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libslversion.a
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libn3d3a.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.utils.cpuctrl.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libfmmt6630.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam3_utils.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libbessound_hd_mtk.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libsysparm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcam.sdkclient.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libhwm.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libgpu_aux.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libMtkOmxCore.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libem_support_jni.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libaudiocompensationfilter.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcustom_prop.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libpq_prot.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libcurl.so
/home/olegsvs/ark_benefit_mt7/android_vendor_ark_benefit_m7/proprietary/system/lib64/libmmprofile_jni.so
